config/routes.rb
Rails.application.routes.draw do
  resources :data_import, only: [:new, :create]
  resources :parcels
  root 'parcels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parcel.rb
class Parcel < ApplicationRecord
  require 'csv'

  geocoded_by :generated_address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      parcel_hash = row.to_hash

      parcel = self.new
      parcel.address = parcel_hash["Address"]
      parcel.current_year_value = cleanup_dollar_values_from_csv(parcel_hash["Current Year Total Value"])
      parcel.previous_year_value = cleanup_dollar_values_from_csv(parcel_hash["Previous Year Total Value"])
      parcel.total_taxes = cleanup_dollar_values_from_csv(parcel_hash["Total Taxes"])

      parcel.save
    end
  end

  def generated_address
    self.address + ", Madison, WI"
  end

  def self.cleanup_dollar_values_from_csv(value)
    value.to_s.gsub('$','').to_f
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/data_import_controller.rb
class DataImportController < ApplicationController
  def new
  end

  def create
    if params[:file]
      Parcel.import(params[:file])
    end
    redirect_to root_url
  end
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  before_action :set_parcel, only: [:show, :edit, :update, :destroy]

  # GET /parcels
  # GET /parcels.json
  def index
    @parcels = Parcel.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /parcels/1
  # GET /parcels/1.json
  def show
  end

  # GET /parcels/new
  def new
    @parcel = Parcel.new
  end

  # GET /parcels/1/edit
  def edit
  end

  # POST /parcels
  # POST /parcels.json
  def create
    @parcel = Parcel.new(parcel_params)

    respond_to do |format|
      if @parcel.save
        format.html { redirect_to @parcel, notice: 'Parcel was successfully created.' }
        format.json { render :show, status: :created, location: @parcel }
      else
        format.html { render :new }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parcels/1
  # PATCH/PUT /parcels/1.json
  def update
    respond_to do |format|
      if @parcel.update(parcel_params)
        format.html { redirect_to @parcel, notice: 'Parcel was successfully updated.' }
        format.json { render :show, status: :ok, location: @parcel }
      else
        format.html { render :edit }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcels/1
  # DELETE /parcels/1.json
  def destroy
    @parcel.destroy
    respond_to do |format|
      format.html { redirect_to parcels_url, notice: 'Parcel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parcel
      @parcel = Parcel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parcel_params
      params.require(:parcel).permit(:address, :current_year_value, :previous_year_value, :total_taxes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_import_helper.rb
module DataImportHelper
end

app/helpers/parcels_helper.rb
module ParcelsHelper
  def display_us_dollar(value)
    "$#{Money.new(value, "USD")}"
  end
end

app/views/data_import/create.html.erb
<h1>DataImport#create</h1>
<p>Find me in app/views/data_import/create.html.erb</p>

app/views/data_import/new.html.erb
  <%= form_tag data_import_index_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MadisonProperties</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js"> </script>

  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/parcels/_form.html.erb
<%= form_for(parcel) do |f| %>
  <% if parcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parcel.errors.count, "error") %> prohibited this parcel from being saved:</h2>

      <ul>
      <% parcel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :current_year_value %>
    <%= f.text_field :current_year_value %>
  </div>

  <div class="field">
    <%= f.label :previous_year_value %>
    <%= f.text_field :previous_year_value %>
  </div>

  <div class="field">
    <%= f.label :total_taxes %>
    <%= f.text_field :total_taxes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parcels/edit.html.erb
<h1>Editing Parcel</h1>

<%= render 'form', parcel: @parcel %>

<%= link_to 'Show', @parcel %> |
<%= link_to 'Back', parcels_path %>

app/views/parcels/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <p id="notice"><%= notice %></p>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
  <h1>Parcels</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Address</th>
          <th>Current year value</th>
          <th>Previous year value</th>
          <th>Total taxes</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody id="parcels">
      </tbody>
    </table>
  </div>
</div>

<img src='http://www.fostersystems.com/ccdata/images/spinner.gif' id='next_page_spinner' />

<br>

<%= link_to 'New Parcel', new_parcel_path %>

<%= javascript_include_tag 'pagination' %>

app/views/parcels/new.html.erb
<h1>New Parcel</h1>

<%= render 'form', parcel: @parcel %>

<%= link_to 'Back', parcels_path %>

app/views/parcels/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <p id="notice"><%= notice %></p>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <p>
      <strong>Address:</strong> <%= @parcel.address %>
    </p>

    <p>
      <strong>Current year value:</strong> <%= @parcel.current_year_value %>
    </p>

    <p>
      <strong>Previous year value:</strong> <%= @parcel.previous_year_value %>
    </p>

    <p>
      <strong>Total taxes:</strong> <%= @parcel.total_taxes %>
    </p>
  </div>

  <div class="col-lg-8">
    <!-- inside the right column -->
    <div class="row">
      <div class="col-lg-12" id="weather-data">
        <h3>Weather</h3>
        <%= image_tag("http://www.fostersystems.com/ccdata/images/spinner.gif", :id => 'next_page_spinner') %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back', parcels_path %>



<!-- at the bottom of the page -->
<%= javascript_include_tag 'weather' %>

<script>
  <% if @parcel.latitude && @parcel.longitude %>
  var url =<%=raw "'http://api.openweathermap.org/data/2.5/weather?lat=#{@parcel.latitude}&lon=#{@parcel.longitude}&appid=#{ENV['weather_api']}'" %>
  <% else %>
  var url =<%=raw "'http://api.openweathermap.org/data/2.5/weather?q=madison,wi,us&appid=#{ENV['weather_api']}'" %>
  <% end %>
  window.getWeather(url);
</script>